ci: ignore sdk install failure

diff --git a/.github/workflows/develop.yaml b/.github/workflows/develop.yaml
--- a/.github/workflows/develop.yaml
+++ b/.github/workflows/develop.yaml
@@ -128,8 +128,10 @@ jobs:
         with:
           python-version: '3.13'
         if: "${{ env.BUILD_WATCH == 'true' }}"
+        # Sometimes SDK installation exits with exit code 1, but still succeeds. 
+        # We can just ignore failures here, as watchapp build will fail anyway even if the SDK is faulty
       - name: Install pebble SDK
-        run: "uv tool install pebble-tool && pebble sdk install latest"
+        run: "uv tool install pebble-tool && (pebble sdk install latest || true)"
         if: "${{ env.BUILD_WATCH == 'true' }}"
       - name: Globally enable build cache and parallel execution
         run: "mkdir -p ~/.gradle && echo -e 'org.gradle.caching=true\norg.gradle.parallel=true' >> ~/.gradle/gradle.properties"
